name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - 'railway.json'
      - '.github/workflows/backend-ci.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package.json'

      - name: Install deps
        run: npm ci

      - name: Basic syntax check
        run: node -e "require('fs').readdirSync('.') && console.log('Backend files present')"

      - name: Run tests (if any)
        run: |
          npm test --silent || echo "No tests configured. Skipping."
